########################################
#   Spring配置
########################################
spring:
  profiles:
    active: dev
  application:
    name: BOOT-CONSUMER

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
